// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kalilventura/vehicle-management-payment/internal/payments"
	"github.com/kalilventura/vehicle-management-payment/internal/payments/domain/commands"
	"github.com/kalilventura/vehicle-management-payment/internal/payments/infrastructure/controllers"
	"github.com/kalilventura/vehicle-management-payment/internal/payments/infrastructure/repositories"
	"github.com/kalilventura/vehicle-management-payment/internal/payments/infrastructure/services"
	"github.com/kalilventura/vehicle-management-payment/internal/shared/domain/entities"
	"github.com/kalilventura/vehicle-management-payment/internal/shared/infrastructure/configuration"
	"os"
	"strconv"
)

import (
	_ "github.com/kalilventura/vehicle-management-payment/cmd/docs"
)

// Injectors from wire.go:

func InjectModules() []entities.HTTPModule {
	databaseSettings := injectDatabaseSettings()
	db := configuration.NewDatabaseClient(databaseSettings)
	gormPaymentsRepository := repositories.NewGormPaymentsRepository(db)
	paymentSettings := injectPaymentSettings()
	stripePaymentService := services.NewStripePaymentService(paymentSettings)
	savePaymentCommand := commands.NewSavePaymentCommand(gormPaymentsRepository, stripePaymentService)
	processPaymentController := controllers.NewProcessPaymentController(savePaymentCommand)
	updatePaymentCommand := commands.NewUpdatePaymentCommand(gormPaymentsRepository)
	webhookSettings := injectWebhookSettings()
	stripeWebhookProcessor := services.NewStripeWebhookProcessor(webhookSettings)
	webhookPaymentController := controllers.NewWebhookPaymentController(updatePaymentCommand, stripeWebhookProcessor)
	module := payments.NewModule(processPaymentController, webhookPaymentController)
	v := newModules(module)
	return v
}

// wire.go:

func InjectSettings() *entities.Settings {
	port, _ := strconv.Atoi(os.Getenv("PORT"))
	return &entities.Settings{port}
}

func injectDatabaseSettings() *entities.DatabaseSettings {
	host := os.Getenv("DB_HOST")
	name := os.Getenv("DB_NAME")
	port := os.Getenv("DB_PORT")
	user := os.Getenv("DB_USER")
	password := os.Getenv("DB_PASSWORD")
	dbSSL := os.Getenv("DB_SSL")
	return entities.NewDatabaseSettings(
		host,
		name,
		port,
		user,
		password,
		dbSSL,
	)
}

func injectPaymentSettings() *entities.PaymentSettings {
	stripeKey := os.Getenv("STRIPE_KEY")
	return &entities.PaymentSettings{stripeKey}
}

func injectWebhookSettings() *entities.WebhookSettings {
	stripeKey := os.Getenv("STRIPE_WEBHOOK_KEY")
	return &entities.WebhookSettings{stripeKey}
}

func newModules(paymentsModule *payments.Module) []entities.HTTPModule {
	return []entities.HTTPModule{
		paymentsModule,
	}
}
