services:
  vehicle_payment_database:
    container_name: vehicle_payment_database
    image: postgres:17.6-alpine3.22
    restart: on-failure
    environment:
      - 'POSTGRES_DB=vehicle_payment'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5433:5432'
    volumes:
      - vehicle_payment_database-data:/var/lib/postgresql/data
    networks:
      - management-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2GB'

  vehicle_payment:
    container_name: vehicle_payment
    env_file:
      - .env
    build:
      context: ../.
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - vehicle_payment_database
    networks:
      - management-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

volumes:
  vehicle_payment_database-data:

networks:
  management-network:
    driver: bridge
